# -*- coding: utf-8 -*-
"""scratchpad

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/empty.ipynb
"""

import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(0, 10, 100)


y = np.sin(x)


plt.plot(x, y, label='Sinus(x)', color='blue')


plt.title('Sinus Funksiyasining Grafiği')
plt.xlabel('X qiymatlari')
plt.ylabel('Y qiymatlari')


plt.legend()
plt.grid(True)


plt.show()

import numpy as np
import matplotlib.pyplot as plt


x = np.random.uniform(0, 10, 50)
y = np.random.uniform(0, 10, 50)

plt.scatter(x, y, label='Nuqtalar', color='blue')


plt.title('Tasodifiy Nuqtalar Scatter Grafiği')
plt.xlabel('X qiymatlari')
plt.ylabel('Y qiymatlari')


plt.legend()


plt.grid(True)


plt.show()

import pandas as pd


url = "https://raw.githubusercontent.com/Zulayho06/Maxsus-topshiriq/main/WHO%20COVID-19%20cases.csv"
df = pd.read_csv(url)


print("DataFrame Ma'lumotlari:")
df.info()


print("\nUstunlar ro'yxati:")
print(df.columns)


print("\nDataFrame'ning bosh qismini ko'rib chiqish:")
print(df.head())


covid_by_country = df.groupby('Country')['Cumulative_cases'].sum().reset_index()


covid_by_country = covid_by_country.sort_values(by='Cumulative_cases', ascending=False)

print("\nEng yuqori tasdiqlangan holatlar bo'yicha 10 ta davlat:")
print(covid_by_country.head(10))


usa_data = df[df['Country'] == 'USA']


print("\nUSA bo'yicha tasdiqlangan COVID-19 holatlari:")
print(usa_data[['Date_reported', 'Cumulative_cases']].tail())



india_data = df[df['Country'] == 'India']


print("\nIndia bo'yicha tasdiqlangan COVID-19 holatlari:")
print(india_data[['Date_reported', 'Cumulative_cases']].tail())

import cv2
import matplotlib.pyplot as plt
from google.colab import files


uploaded = files.upload()


image_path = list(uploaded.keys())[0]


img = cv2.imread(image_path)


gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


plt.figure(figsize=(10, 5))


plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title('Original Rasm')
plt.axis('off')


plt.subplot(1, 2, 2)
plt.imshow(gray_img, cmap='gray')
plt.title('Oq-Qora Rasm')
plt.axis('off')

plt.tight_layout()
plt.show()

import cv2
import matplotlib.pyplot as plt
from google.colab import files


uploaded = files.upload()


image_path = list(uploaded.keys())[0]


img = cv2.imread(image_path)


gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


plt.figure(figsize=(10, 5))


plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title('Original Rasm')
plt.axis('off')


plt.subplot(1, 2, 2)
plt.imshow(gray_img, cmap='gray')
plt.title('Oq-Qora Rasm')
plt.axis('off')

plt.tight_layout()
plt.show()

import cv2
import matplotlib.pyplot as plt
from google.colab import files


uploaded = files.upload()


image_path = list(uploaded.keys())[0]


img = cv2.imread(image_path)


gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


plt.figure(figsize=(10, 5))


plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title('Original Rasm')
plt.axis('off')


plt.subplot(1, 2, 2)
plt.imshow(gray_img, cmap='gray')
plt.title('Oq-Qora Rasm')
plt.axis('off')

plt.tight_layout()
plt.show()